Using working directory as pilot root directory
BoomingTech/Pilot pull request #238
Opened 2022-06-02 01:24 UTC by ShenMian

原本这么做可能是因为 Visual Studio 的调试器默认工作目录为源文件所在的目录, 通过在 CMake 中提前指定工作目录来使 Visual Studio 和其他 IDE 的行为保持一直来避免这个问题.  
新使用的 CMake 代码适用于 3.8 以及之后版本, 符合当前 CMake 版本最低要求. 不过此修改将不再允许 Visual Studio 直接打开该项目, 只能使用 CMake 生成的项目解决方案文件(.sln)打开.  
#225 
(提交时发现已经存在相关PR, 这里给出另一个解决方案)

2022-06-02 08:57 UTC, Ol6rin commented
#228 这个主要是为了解决部署版本无法拷贝至其他位置运行的问题，如果只是单纯修改运行时根目录的获取，资产是没办法跟着引擎走的。#228 目前Windows已经测试过，Ubuntu和macOS还在调试中。

2022-06-02 10:28 UTC, Ol6rin requested changes

2022-06-02 10:28 UTC, Ol6rin commented on engine/source/editor/CMakeLists.txt
> +set_target_properties(${TARGET_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${BINARY_ROOT_DIR}")
这里加一个编译环境是MSVC的判断，可以避免在其他开发环境下出错

2022-06-02 11:04 UTC, ShenMian commented on engine/source/editor/CMakeLists.txt
> +set_target_properties(${TARGET_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "${BINARY_ROOT_DIR}")
https://cmake.org/cmake/help/latest/prop_tgt/VS_DEBUGGER_WORKING_DIRECTORY.html

2022-06-06 05:36 UTC, Ol6rin approved these changes
Code is ok to me. After testing on Linux and macOS the PR can be merged.

2022-06-07 12:12 UTC, Ol6rin commented
测试下来macOS上使用Xcode编译后无法通过Xcode直接运行，Xcode类似VS有一个Scheme Working Directory的配置，参见cmake文档 [CMake - XCODE_SCHEME_WORKING_DIRECTORY](https://cmake.org/cmake/help/latest/prop_tgt/XCODE_SCHEME_WORKING_DIRECTORY.html)。
bin目录下通过Terminal可以运行，将bin目录拷贝到其他位置也可以。但是通过Finder双击不行，获取当前路径始终为用户根目录。

2022-06-09 09:40 UTC, Ol6rin commented
Ubuntu在某些环境下需要设置cwd才能正常运行。工作目录确实在很多情形下使用起来非常麻烦，综合以上测试情况，我们决定采用区分ini配置文件的方式处理VS和Xcode调试运行读取资源的问题。

2022-06-09 09:40 UTC, closed without merging